version: '3'
services: 
    client:
        image: node:stretch
        command: sh -c "npm install && npm run serve"
        environment: 
            - NODE_ENV=development
            - PORT=8080
        ports: 
            - '8000:8000'
        working_dir: /root/client
        volumes: 
            - ./client:/root/client:cached